### ISSUE TITLE
Incorrect default volume on first load

### ISSUE THREAD

**Issue by sb2bg** [arjohnsonn/Help-Me-Bevo#1]
When installing the extension from the Chrome Web Store, the default volume displays as 0.5 instead of 50. This issue only occurs on the first load after installation. Interestingly, when loading the extension as unpacked, the volume displays correctly, which only makes it more confusing.

**Comment by arjohnsonn** [comment]
Thank you for the issue! This is currently fixed in the latest version; CWS is taking a while for it to approve. I'll leave this open until the new build is up. Then, let me know if it's fixed!

**Comment by arjohnsonn** [comment]
@sb2bg Fixed? Should be updated in v1.2.6; you may need to click Update in the extensions tab.

**Comment by arjohnsonn** [comment]
Implemented checks for volume load in v1.2.6
